/**
 * The standards catalogue.
 *
 * A fire technician works to about thirty documents, and on site the question is
 * almost never "what does the clause say" — it is "which clause is this, and does
 * what I am looking at meet it". This is the index that answers the first half,
 * offline, and points at the app's own calculation for the second.
 *
 * **There is deliberately no field here for a standard's text.** Australian
 * Standards are copyright Standards Australia and are licensed per copy; putting
 * their wording in a repository would redistribute them. What ships is clause
 * numbers, which are facts, and descriptions written here of what each clause
 * governs and which part of this app implements or checks it. Where a technician
 * needs the actual words, the app opens their own licensed copy — imported on the
 * device, never synced and never committed. See src/db/libraryRepo.ts.
 *
 * Queensland legislation and the Queensland Development Code are a different
 * matter — they are Crown material, published free, and are reproduced in full
 * where the app needs them.
 *
 * Clause numbers and titles here were read out of the documents themselves rather
 * than recalled, so they can be trusted as references. A clause with no
 * description is one nobody has written up yet: it is listed so it can be found
 * and cited, and says nothing further rather than inventing a summary.
 */

export type StandardScope = 'design' | 'maintenance' | 'product' | 'legislation' | 'code';

export type StandardStatus = 'current' | 'superseded' | 'amended';

export interface StandardClause {
  /** As printed in the document: "3.5", "10.4", "SECTION 7". */
  ref: string;
  title: string;
  /** What it governs, in our words. Absent where nobody has written it up. */
  covers?: string;
  /** The app route that implements or checks it, where one exists. */
  appFeature?: string;
}

export interface StandardDoc {
  id: string;
  /** "AS 2419.1:2005" — how a technician cites it. */
  designation: string;
  title: string;
  scope: StandardScope;
  status: StandardStatus;
  supersededBy?: string;
  /** App system kinds this document governs, for filtering by what is on site. */
  systems: string[];
  officialUrl: string;
  note?: string;
  clauses: StandardClause[];
}

export const STANDARDS: StandardDoc[] = [
  {
    id: 'as-2419-1-2005',
    designation: "AS 2419.1:2005",
    title: "Fire hydrant installations \u2014 System design, installation and commissioning",
    scope: "design",
    status: "superseded",
    supersededBy: "AS 2419.1:2021",
    systems: ["hydrant", "pump"],
    officialUrl: "https://store.standards.org.au/product/as-2419-1-2005",
    clauses: [
      { ref: "1.1", title: "Scope" },
      { ref: "1.2", title: "Objective" },
      { ref: "1.3", title: "Normative References" },
      { ref: "1.4", title: "Definitions" },
      { ref: "1.5", title: "Symbols" },
      { ref: "2.1", title: "Design Concept" },
      { ref: "2.2", title: "Design Parameters",
        covers: "The design parameters a hydrant system is sized against \u2014 flow, pressure and how many hydrants must run at once. This is what a flow test is measured against, and the figures come from the block plan for the building rather than from the app.",
        appFeature: "tools/hydrant" },
      { ref: "2.3", title: "Required System Performance",
        covers: "The performance the installed system has to deliver. A flow test that misses this is a system failure, not a paperwork one.",
        appFeature: "tools/hydrant" },
      { ref: "3.1", title: "General" },
      { ref: "3.2", title: "Location of On-site Fire Hydrants",
        covers: "Where on-site hydrants may be placed, which sets coverage and therefore which hydrant is the hydraulically most disadvantaged.",
      },
      { ref: "3.3", title: "Open Yard Protection" },
      { ref: "3.4", title: "Marinas" },
      { ref: "3.5", title: "Fire Hydrant Accessibility and Clearance",
        covers: "Accessibility and clearance around a hydrant. A hydrant that cannot be reached or coupled to is a defect even when it flows correctly.",
      },
      { ref: "3.6", title: "Fire Hydrant Cabinets, Enclosures or Recesses" },
      { ref: "4.1", title: "Acceptable Sources of Water Supply" },
      { ref: "4.2", title: "Minimum Water Supply Quantity" },
      { ref: "4.3", title: "On-site Water Storage" },
      { ref: "5.1", title: "General" },
      { ref: "5.2", title: "Water Supplies to Storage Tanks" },
      { ref: "5.3", title: "Effective Capacity" },
      { ref: "5.4", title: "Storage Tank Connections, Valves and Accessories" },
      { ref: "6.1", title: "General" },
      { ref: "6.2", title: "Pumpset Configurations" },
      { ref: "6.3", title: "Electric Driver Isolating Switches" },
      { ref: "6.4", title: "Pumproom" },
      { ref: "7.1", title: "General" },
      { ref: "7.1.1", title: "Hydrant block plan",
        covers: "The block plan at the booster: the drawing the brigade reads on arrival and the source of the flow and pressure duty a test is assessed against. Without it, a flow test has no pass mark.",
        appFeature: "tools/hydrant" },
      { ref: "7.2", title: "When A Booster Assembly Is Required",
        covers: "When a fire brigade booster assembly is required at all.",
      },
      { ref: "7.3", title: "Location" },
      { ref: "7.4", title: "Fire Brigade Booster Assembly Arrangement" },
      { ref: "7.5", title: "Booster in Parallel with Pumps" },
      { ref: "7.6", title: "Boosters in Series (relay) with Pumps" },
      { ref: "7.7", title: "Fire Brigade Relay Pumps" },
      { ref: "7.8", title: "Fire Brigade Booster Assembly Enclosure" },
      { ref: "7.10", title: "Signage" },
      { ref: "7.11", title: "Block Plan",
        covers: "The booster block plan \u2014 the drawing the brigade reads on arrival, and the source of the flow and pressure duty a test is assessed against.",
        appFeature: "tools/hydrant" },
      { ref: "8.1", title: "Pipes and Pipe Settings" },
      { ref: "8.2", title: "Pipe and Pipe Fitting Specifications" },
      { ref: "8.3", title: "Metal Pipe Joints" },
      { ref: "8.4", title: "Hydrostatic Pressure Test",
        covers: "The hydrostatic pressure test on pipework: the pressure held, for how long, and what loss is acceptable. Part B of Queensland Form 72 records exactly this.",
        appFeature: "site/form72" },
      { ref: "8.5", title: "Pipework Design" },
      { ref: "8.6", title: "System Protection and Identification" },
      { ref: "8.7", title: "Support of Fire Hydrant Pipework" },
      { ref: "8.8", title: "Thrust Blocks and Anchors" },
      { ref: "9.1", title: "General" },
      { ref: "9.2", title: "Fire Hose" },
      { ref: "9.3", title: "Pressure Gauges",
        covers: "Pressure gauges \u2014 which matters for testing because a gauge outside its calibration makes every reading on the certificate unusable. Form 72 Part C records gauge serial numbers and calibration dates for that reason.",
        appFeature: "site/form72" },
      { ref: "9.4", title: "Backflow Prevention" },
      { ref: "10.1", title: "General" },
      { ref: "10.2", title: "Hydrostatic Tests" },
      { ref: "10.3", title: "Commissioning Tests" },
      { ref: "10.4", title: "Systems That Incorporate A Booster",
        covers: "Commissioning tests for a system with a booster. Form 72 Part E records the booster test against this.",
        appFeature: "site/form72" },
      { ref: "10.5", title: "Systems That Incorporate A Pump",
        covers: "Commissioning tests for a system with a pump.",
        appFeature: "site/form72" },
      { ref: "10.6", title: "Systems That Incorporate A Tank" },
      { ref: "10.7", title: "Recording of Commissioning (verification) Tests" },
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "System Design" },
      { ref: "SECTION 3", title: "Location and Other Provisions" },
      { ref: "SECTION 4", title: "Water Supplies" },
      { ref: "SECTION 5", title: "Water Storage" },
      { ref: "SECTION 6", title: "Pumpsets" },
      { ref: "SECTION 7", title: "Fire Brigade Booster Assembly" },
      { ref: "SECTION 8", title: "Pipework and Valves" },
      { ref: "SECTION 9", title: "Ancillary Equipment" },
      { ref: "SECTION 10", title: "Commissioning" },
    ],
  },
  {
    id: 'as-nzs-2293-2-1995',
    designation: "AS/NZS 2293.2:1995",
    title: "Emergency escape lighting and exit signs for buildings \u2014 Inspection and maintenance",
    scope: "maintenance",
    status: "amended",
    systems: ["emergency-lighting"],
    officialUrl: "https://store.standards.org.au/product/as-nzs-2293-2-1995",
    note: "Called up by QDC MP 6.1 as the maintenance standard for emergency lighting in Queensland, alongside AS 1851.",
    clauses: [
      { ref: "1.1", title: "Scope" },
      { ref: "1.2", title: "Referenced Documents" },
      { ref: "1.3", title: "Definitions" },
      { ref: "1.4", title: "General Requirements" },
      { ref: "2.1", title: "Required Procedures" },
      { ref: "2.2", title: "Six-monthly Procedures",
        covers: "Six-monthly procedures for centrally supplied emergency lighting \u2014 including the discharge test that proves the fittings run for their rated duration.",
        appFeature: "tools/emergency-lighting" },
      { ref: "2.3", title: "Twelve-monthly Procedures",
        covers: "Twelve-monthly procedures for centrally supplied systems.",
        appFeature: "tools/emergency-lighting" },
      { ref: "3.1", title: "Required Procedures" },
      { ref: "3.2", title: "Six-monthly Procedures",
        covers: "Six-monthly procedures for single-point (self-contained) fittings. Most of the 4,203 emergency lighting assets on the book are these.",
        appFeature: "tools/emergency-lighting" },
      { ref: "3.3", title: "Twelve-monthly Procedures",
        covers: "Twelve-monthly procedures for single-point fittings.",
        appFeature: "tools/emergency-lighting" },
      { ref: "3.4", title: "Battery Replacement",
        covers: "Battery replacement for single-point fittings \u2014 the lifecycle finding behind most emergency lighting failures.",
        appFeature: "tools/emergency-lighting" },
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "Inspection and Maintenance Procedures for Central" },
      { ref: "SECTION 3", title: "Inspection and Maintenance Procedures for Single-point" },
    ],
  },
  {
    id: 'as-2444-2001',
    designation: "AS 2444:2001",
    title: "Portable fire extinguishers and fire blankets \u2014 Selection and location",
    scope: "design",
    status: "superseded",
    supersededBy: "AS 2444:2021",
    systems: ["extinguisher"],
    officialUrl: "https://store.standards.org.au/product/as-2444-2001",
    clauses: [
      { ref: "1.1", title: "Scope" },
      { ref: "1.2", title: "Application" },
      { ref: "1.3", title: "Referenced and Related Documents" },
      { ref: "1.4", title: "Definitions" },
      { ref: "2.1", title: "General" },
      { ref: "2.2", title: "Classification and Rating",
        covers: "Classification and rating of extinguishers \u2014 the letters and numbers on the label that say which fires it is rated for.",
        appFeature: "tools/extinguisher" },
      { ref: "3.1", title: "General" },
      { ref: "3.2", title: "Extinguisher Location",
        covers: "Where an extinguisher may be located, which drives the travel-distance check on a service.",
        appFeature: "tools/extinguisher" },
      { ref: "3.3", title: "Extinguisher Location Signs",
        covers: "Extinguisher location signs. A missing or wrong sign is one of the commonest coded defects raised.",
        appFeature: "tools/extinguisher" },
      { ref: "3.4", title: "Visibility" },
      { ref: "3.5", title: "Support" },
      { ref: "3.6", title: "Cabinet or Enclosure" },
      { ref: "3.7", title: "Record of Type and Disposition" },
      { ref: "3.8", title: "Fire Points" },
      { ref: "3.9", title: "Environment" },
      { ref: "4.1", title: "General" },
      { ref: "4.2", title: "Class A Fire Risks",
        covers: "Distribution for Class A fire risks \u2014 how many extinguishers and how far apart.",
        appFeature: "tools/extinguisher" },
      { ref: "4.3", title: "Class B Fire Risks",
        covers: "Distribution for Class B fire risks.",
        appFeature: "tools/extinguisher" },
      { ref: "4.4", title: "Complementary Protection" },
      { ref: "5.1", title: "General" },
      { ref: "5.2", title: "Remote Areas" },
      { ref: "5.3", title: "Accessibility" },
      { ref: "5.4", title: "Selection Factors" },
      { ref: "6.1", title: "General" },
      { ref: "6.2", title: "Selection" },
      { ref: "6.3", title: "Location",
        covers: "Where a fire blanket goes \u2014 the kitchen placement question that comes up on nearly every aged-care and hospitality site.",
      },
      { ref: "6.4", title: "Fire Blanket Location Signs" },
      { ref: "6.5", title: "Mounting" },
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "Selection of Portable Fire Extinguishers" },
      { ref: "SECTION 3", title: "Location of Portable Fire Extinguishers" },
      { ref: "SECTION 4", title: "Distribution of Portable Fire Extinguishers in Buildings" },
      { ref: "SECTION 5", title: "Selection and Distribution of Portable Fire" },
      { ref: "SECTION 6", title: "Selection and Location of Fire Blankets" },
    ],
  },
  {
    id: 'as-1670-4-2018',
    designation: "AS 1670.4:2018",
    title: "Fire detection, warning, control and intercom systems \u2014 System design, installation and commissioning, Part 4: Emergency warning and intercom systems",
    scope: "design",
    status: "current",
    systems: ["ews"],
    officialUrl: "https://store.standards.org.au/product/as-1670-4-2018",
    clauses: [
      { ref: "1.1", title: "Scope" },
      { ref: "1.2", title: "Application" },
      { ref: "1.3", title: "Normative References" },
      { ref: "1.4", title: "Definitions" },
      { ref: "1.5", title: "Abbreviations" },
      { ref: "1.6", title: "Measurements" },
      { ref: "1.6.1", title: "Tolerance" },
      { ref: "1.6.2", title: "Spacing" },
      { ref: "1.7", title: "System Design" },
      { ref: "1.7.1", title: "General" },
      { ref: "1.7.2", title: "Baseline Data" },
      { ref: "1.7.3", title: "Alterations to Existing Systems" },
      { ref: "1.8", title: "Application of Normative References" },
      { ref: "2.1", title: "Components" },
      { ref: "2.1.1", title: "General" },
      { ref: "2.1.2", title: "Components Emergency Warning System (ews)" },
      { ref: "2.1.3", title: "Components Emergency Intercom System (eis)" },
      { ref: "2.1.4", title: "Connectable Devices" },
      { ref: "2.2", title: "Emergency Zone Limitations" },
      { ref: "2.3", title: "Networked CIE" },
      { ref: "2.4", title: "Distributed Parts of CIE" },
      { ref: "2.5", title: "Transmission Path Faults" },
      { ref: "3.1", title: "General" },
      { ref: "3.2", title: "Control of Connectable Devices" },
      { ref: "3.2.1", title: "General" },
      { ref: "3.2.2", title: "Supervision" },
      { ref: "3.3", title: "Control and Indicating Equipment (CIE)",
        covers: "Location and access for control and indicating equipment.",
      },
      { ref: "3.3.1", title: "Location" },
      { ref: "3.3.2", title: "Covering Door" },
      { ref: "3.3.3", title: "Clearance" },
      { ref: "3.3.4", title: "Working Environment" },
      { ref: "3.3.5", title: "Emergency Zone Block Plan" },
      { ref: "3.4", title: "Equipment Cabinets" },
      { ref: "3.4.1", title: "Fire Isolation" },
      { ref: "3.4.2", title: "Labelling" },
      { ref: "3.5", title: "Power Supply Equipment (PSE)",
        covers: "Power supply equipment, including the standby capacity calculation the battery calculator implements.",
        appFeature: "tools/battery" },
      { ref: "3.5.1", title: "General" },
      { ref: "3.5.2", title: "Main Power Source" },
      { ref: "3.5.3", title: "Standby Power Source" },
      { ref: "3.5.4", title: "Power Supply Equipment Rating" },
      { ref: "3.5.5", title: "Standby Power Source Capacity" },
      { ref: "3.5.6", title: "Battery Capacity Calculation" },
      { ref: "3.5.7", title: "PSE Selection" },
      { ref: "3.5.8", title: "Batteries and Cabinets \u2014 Location" },
      { ref: "3.5.9", title: "Battery Wiring" },
      { ref: "3.6", title: "Cabling Systems" },
      { ref: "3.6.1", title: "General" },
      { ref: "3.6.2", title: "Conductors" },
      { ref: "3.6.3", title: "Cable Marking" },
      { ref: "3.6.4", title: "Termination" },
      { ref: "3.6.5", title: "Stress on Conductors" },
      { ref: "3.6.6", title: "Joints" },
      { ref: "3.6.7", title: "Transmission Path Supervision" },
      { ref: "3.6.8", title: "Transmission Path Protection" },
      { ref: "3.7", title: "Emergency Procedures" },
      { ref: "3.9", title: "Commissioning of System" },
      { ref: "4.1", title: "General" },
      { ref: "4.2", title: "Functional Requirements" },
      { ref: "4.2.1", title: "Distribution of Audible Emergency Warning Signals" },
      { ref: "4.2.2", title: "Initiation" },
      { ref: "4.2.3", title: "Locations of Manual Call Point (MCP)" },
      { ref: "4.2.4", title: "Manual Call Points (MCP)" },
      { ref: "4.3", title: "Delay Before Entering Emergency Condition" },
      { ref: "4.4", title: "Alert Signal Duration in Automatic Mode" },
      { ref: "4.5", title: "Evacuate Signal",
        covers: "The evacuate signal itself.",
      },
      { ref: "4.6", title: "Visual Alarm Signals",
        covers: "Visual alarm devices, for areas where an audible signal cannot be relied on.",
      },
      { ref: "4.7", title: "Output from Emergency Loudspeakers",
        covers: "Output from emergency loudspeakers \u2014 the sound pressure level the warning signal has to reach, and the ceiling it must not exceed.",
        appFeature: "tools/spl" },
      { ref: "4.8", title: "Speech Messages" },
      { ref: "4.9", title: "Intelligibility",
        covers: "Intelligibility \u2014 a speech message that is audible but not understandable does not do its job. Measured, not judged by ear.",
        appFeature: "tools/spl" },
      { ref: "4.10", title: "Interconnection to the Fdcie" },
      { ref: "4.11", title: "Competing Sound Systems" },
      { ref: "4.12", title: "Use of the Emergency Warning System for Non-emergency Purposes" },
      { ref: "5.1", title: "General" },
      { ref: "5.2", title: "Eicie" },
      { ref: "5.3", title: "Warden Intercom Points (WIP)",
        covers: "Warden intercom points \u2014 location, sound levels, crosstalk and the audible call signal.",
      },
      { ref: "5.3.1", title: "General" },
      { ref: "5.3.2", title: "Sound Levels During an Emergency" },
      { ref: "5.3.3", title: "Location" },
      { ref: "5.3.4", title: "Crosstalk, Clarity and Intelligibility" },
      { ref: "5.3.5", title: "Audible Call Signal" },
    ],
  },
  {
    id: 'as-1670-4-2015',
    designation: "AS 1670.4:2015",
    title: "Fire detection, warning, control and intercom systems \u2014 Part 4: Emergency warning and intercom systems",
    scope: "design",
    status: "superseded",
    supersededBy: "AS 1670.4:2018",
    systems: ["ews"],
    officialUrl: "https://store.standards.org.au/product/as-1670-4-2015",
    clauses: [
      { ref: "1.1", title: "Scope" },
      { ref: "1.2", title: "Application" },
      { ref: "1.3", title: "Normative References" },
      { ref: "1.4", title: "Definitions" },
      { ref: "1.5", title: "Abbreviations" },
      { ref: "1.6", title: "Tolerances" },
      { ref: "1.7", title: "Baseline Data" },
      { ref: "2.1", title: "Control and Indicating Equipment" },
      { ref: "2.2", title: "Distributed EWCIE and Eicie Protection" },
      { ref: "2.3", title: "Wiring" },
      { ref: "2.4", title: "Emergency Procedures" },
      { ref: "3.1", title: "General" },
      { ref: "3.2", title: "Primary Power Source" },
      { ref: "3.3", title: "Standby Power Source" },
      { ref: "3.4", title: "Power Supply Equipment Rating" },
      { ref: "3.5", title: "Standby Power Source Capacity" },
      { ref: "3.6", title: "Battery Capacity" },
      { ref: "3.7", title: "Battery Charging Current" },
      { ref: "3.8", title: "Batteries and Enclosures" },
      { ref: "3.9", title: "Ancillary Loads" },
      { ref: "4.1", title: "General" },
      { ref: "4.2", title: "Components" },
      { ref: "4.3", title: "Functional Requirements" },
      { ref: "4.4", title: "Loudspeakers, Vwd, Vad and Other Devices" },
      { ref: "5.1", title: "General" },
      { ref: "5.2", title: "Components" },
      { ref: "5.3", title: "Eicie" },
      { ref: "5.4", title: "Warden Intercom Points" },
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "General Installation Requirements" },
      { ref: "SECTION 3", title: "Power Supply" },
      { ref: "SECTION 4", title: "Emergency Warning System Installation Requirements" },
      { ref: "SECTION 5", title: "Emergency Intercom System Installation Requirements" },
    ],
  },
  {
    id: 'as-1670-4-2004',
    designation: "AS 1670.4:2004",
    title: "Fire detection, warning, control and intercom systems \u2014 Part 4: Emergency warning and intercom systems",
    scope: "design",
    status: "superseded",
    supersededBy: "AS 1670.4:2015",
    systems: ["ews"],
    officialUrl: "https://store.standards.org.au/product/as-1670-4-2004",
    clauses: [
      { ref: "1.1", title: "Scope" },
      { ref: "1.2", title: "Application" },
      { ref: "1.3", title: "Referenced Documents" },
      { ref: "1.4", title: "Definitions" },
      { ref: "1.5", title: "Compliance with Other Standards" },
      { ref: "1.6", title: "Interpretation of Specified Limiting Values" },
      { ref: "2.1", title: "Indicator Panels" },
      { ref: "2.2", title: "Distributed Equipment Protection" },
      { ref: "2.3", title: "Wiring" },
      { ref: "2.4", title: "Emergency Procedures" },
      { ref: "3.1", title: "General" },
      { ref: "3.2", title: "Main Power Source" },
      { ref: "3.3", title: "Stand-by Power Source" },
      { ref: "3.4", title: "Power Source Rating" },
      { ref: "3.5", title: "Battery Capacity" },
      { ref: "3.6", title: "Charging Current" },
      { ref: "3.7", title: "Batteries and Enclosures" },
      { ref: "3.8", title: "Ancillary Loads" },
      { ref: "4.1", title: "General" },
      { ref: "4.2", title: "Components" },
      { ref: "4.3", title: "Functional Requirements" },
      { ref: "4.4", title: "Wiring" },
      { ref: "4.5", title: "Loudspeakers" },
      { ref: "5.1", title: "General" },
      { ref: "5.2", title: "Components" },
      { ref: "5.3", title: "Warden Intercom Points" },
      { ref: "5.4", title: "Wiring" },
      { ref: "6.1", title: "General Checks" },
      { ref: "6.2", title: "Specific Sound System Checks" },
      { ref: "6.3", title: "Specific Intercom System Checks" },
      { ref: "6.4", title: "Documentation" },
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "General Installation Requirements" },
      { ref: "SECTION 3", title: "Power Supply" },
      { ref: "SECTION 4", title: "Sound System Installation Requirements" },
      { ref: "SECTION 5", title: "Intercom System Installation Requirements" },
      { ref: "SECTION 6", title: "Commissioning" },
    ],
  },
  {
    id: 'as-1670-1-2004',
    designation: "AS 1670.1:2004",
    title: "Fire detection, warning, control and intercom systems \u2014 Part 1: Fire",
    scope: "design",
    status: "superseded",
    supersededBy: "AS 1670.1:2018",
    systems: ["detection", "aspirating"],
    officialUrl: "https://store.standards.org.au/product/as-1670-1-2004",
    clauses: [
      { ref: "1.1", title: "Scope" },
      { ref: "1.2", title: "Application" },
      { ref: "1.3", title: "Referenced Documents" },
      { ref: "1.4", title: "Definitions" },
      { ref: "1.5", title: "Interpretation of Specified Limiting Values" },
      { ref: "2.1", title: "Components" },
      { ref: "2.2", title: "Separation of Systems" },
      { ref: "2.3", title: "Designated Entry Point" },
      { ref: "2.4", title: "Alarm Zone Limitations" },
      { ref: "2.5", title: "Addressable Circuits" },
      { ref: "2.6", title: "Distributed Systems" },
      { ref: "3.1", title: "General" },
      { ref: "3.2", title: "Alarm Acknowledgment Facility" },
      { ref: "3.4", title: "Alterations to Existing Installations" },
      { ref: "3.5", title: "Multi-point Aspirating Smoke Detectors" },
      { ref: "3.6", title: "Control of Ancillary Devices" },
      { ref: "3.7", title: "Detector Alarm Indication" },
      { ref: "3.8", title: "EXTERNAL ALARM INDICATION",
        covers: "The external device that tells an arriving brigade which building is in alarm.",
      },
      { ref: "3.8", title: "External alarm indication",
        covers: "The external device that tells an arriving brigade which building is in alarm.",
      },
      { ref: "3.9", title: "FIRE INDICATOR PANEL",
        covers: "Clear space required in front of the fire indicator panel. Checked on the monthly routine, and one of the most common obstruction defects raised.",
        appFeature: "tools/routines" },
      { ref: "3.9", title: "Fire panel clearance",
        covers: "Clear space required in front of the fire indicator panel. Checked on the monthly routine, and one of the most common obstruction defects raised.",
        appFeature: "tools/routines" },
      { ref: "3.10", title: "ZONE BLOCK PLAN",
        covers: "The zone block plan at the panel. The app generates this from the imported panel configuration, so the chart cannot disagree with the panel it describes.",
        appFeature: "site/zones" },
      { ref: "3.10", title: "Zone block plan",
        covers: "The zone block plan at the panel. The app generates this from the imported panel configuration, so the chart cannot disagree with the panel it describes.",
        appFeature: "site/zones" },
      { ref: "3.11", title: "Co Fire Detector Labelling" },
      { ref: "3.12", title: "Fire Suppression System" },
      { ref: "3.13", title: "Flow/pressure Switches" },
      { ref: "3.14", title: "Intermixing of Actuating Devices" },
      { ref: "3.15", title: "Manual Call Points" },
      { ref: "3.16", title: "Power Sources" },
      { ref: "3.17", title: "Remote Indicators for Fire Detectors" },
      { ref: "3.18", title: "Remote Monitoring" },
      { ref: "3.19", title: "Smoke and Fire Door Release Control" },
      { ref: "3.20", title: "Subindicator Panel (sip)" },
      { ref: "3.21", title: "Valve Monitoring Devices" },
      { ref: "3.22", title: "Occupant Warning" },
      { ref: "3.23", title: "Wire-free Alarm Zone Circuits" },
      { ref: "3.24", title: "Wiring" },
      { ref: "3.25", title: "Location of Detectors" },
      { ref: "3.26", title: "Locations Where Detectors Are Not Required" },
      { ref: "3.27", title: "Fire Brigade Panel" },
      { ref: "3.28", title: "Multi-sensor Detectors" },
      { ref: "4.1", title: "Spacing and Location of Point-type Heat Detectors" },
      { ref: "4.2", title: "Linear Heat Detectors" },
      { ref: "5.1", title: "Spacing and Location of Point-type Detectors" },
      { ref: "5.1.4", title: "Spacing from walls, partitions or air supply openings",
        covers: "How close a detector may be to a wall, a partition or an air supply opening. This is the single most asked question on site, and the reason a detector that looks fine can still be a non-conformance.",
      },
      { ref: "5.1.5", title: "Spacing from lights and ceiling fans",
        covers: "Separation between a detector and light fittings or ceiling fans, which disturb the airflow the detector depends on.",
      },
      { ref: "5.2", title: "Multi-point Aspirating Smoke Detectors" },
      { ref: "6.1", title: "Location" },
      { ref: "6.2", title: "Spacing" },
      { ref: "7.1", title: "General" },
      { ref: "7.2", title: "Documentation" },
      { ref: "7.3", title: "Log" },
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "System Configuration" },
      { ref: "SECTION 3", title: "Installation Requirements" },
      { ref: "SECTION 4", title: "Heat Detectors" },
      { ref: "SECTION 5", title: "Smoke and Co Fire Detectors" },
      { ref: "SECTION 6", title: "Flame Detectors" },
      { ref: "SECTION 7", title: "Commissioning" },
    ],
  },
  {
    id: 'as-nzs-1850-1997',
    designation: "AS/NZS 1850:1997",
    title: "Portable fire extinguishers \u2014 Classification, rating and performance testing",
    scope: "product",
    status: "superseded",
    systems: ["extinguisher"],
    officialUrl: "https://store.standards.org.au/product/as-nzs-1850-1997",
    clauses: [
      { ref: "1.1", title: "Scope" },
      { ref: "1.2", title: "Referenced Documents" },
      { ref: "1.3", title: "Classification" },
      { ref: "1.4", title: "Rating" },
      { ref: "1.5", title: "Electrical Non-conductivity" },
      { ref: "2.1", title: "General" },
      { ref: "2.2", title: "End-point" },
      { ref: "2.3", title: "Number of Test Fires" },
      { ref: "2.4", title: "Activation of Extinguishers" },
      { ref: "2.5", title: "Storage and Test Temperature" },
      { ref: "2.6", title: "Test Conditions" },
      { ref: "2.7", title: "Discharge Conditions" },
      { ref: "2.8", title: "Test Personnel" },
      { ref: "3.1", title: "Classification and Rating" },
      { ref: "3.2", title: "Wood Crib Test Fire" },
      { ref: "3.3", title: "Observations" },
      { ref: "4.1", title: "Classification and Rating" },
      { ref: "4.2", title: "Flammable Liquid Test Fire" },
      { ref: "4.3", title: "Observations" },
      { ref: "5.1", title: "Capability" },
      { ref: "5.2", title: "Class C Test Fire" },
      { ref: "5.3", title: "Observations" },
      { ref: "6.1", title: "Capability" },
      { ref: "6.2", title: "Discharge Characteristics" },
      { ref: "6.3", title: "Marking" },
      { ref: "7.1", title: "Capability for Use on Electrically Energized Equipment" },
      { ref: "7.2", title: "Electrical Non-conductivity Test" },
      { ref: "7.3", title: "Mounting Target" },
      { ref: "7.4", title: "Connections to Extinguisher and Target" },
      { ref: "7.5", title: "Electrical Circuits" },
      { ref: "7.6", title: "Current Flow Meter" },
      { ref: "7.7", title: "Test Methods" },
      { ref: "8.1", title: "Classification and Rating" },
      { ref: "8.2", title: "Cooking Oil Test Fires" },
      { ref: "8.3", title: "Observations" },
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "General Requirements for Performance Tests" },
      { ref: "SECTION 3", title: "Class A Performance Test" },
      { ref: "SECTION 4", title: "Class B Performance Test" },
      { ref: "SECTION 5", title: "Class C Performance Test" },
      { ref: "SECTION 6", title: "Class D Performance Test" },
      { ref: "SECTION 7", title: "Electrical Non-conductivity Test" },
      { ref: "SECTION 8", title: "Class F Performance Test" },
      { ref: "SECTION 7", title: "E Lectr Ic A L" },
    ],
  },
  {
    id: 'as-2030-1-1999',
    designation: "AS 2030.1:1999",
    title: "The verification, filling, inspection, testing and maintenance of cylinders for storage and transport of compressed gases \u2014 Cylinders for compressed gases other than acetylene",
    scope: "product",
    status: "superseded",
    systems: ["extinguisher"],
    officialUrl: "https://store.standards.org.au/product/as-2030-1-1999",
    note: "The cylinder standard behind extinguisher hydrostatic (pressure) testing.",
    clauses: [
      { ref: "1", title: "Scope" },
      { ref: "2", title: "Referenced Documents" },
      { ref: "3", title: "Definitions" },
      { ref: "4", title: "Cylinder Manufacture" },
      { ref: "5", title: "Fittings and Valve Protection" },
      { ref: "6", title: "Filling" },
      { ref: "7", title: "Gastraffic Change" },
      { ref: "8", title: "Inspection and Testing" },
      { ref: "9", title: "Marking, Identification and Repairs" },
      { ref: "10", title: "Care and Handling" },
      { ref: "11", title: "Records" },
    ],
  },
  {
    id: 'as-2441-2005',
    designation: "AS 2441:2005",
    title: "Installation of fire hose reels",
    scope: "design",
    status: "superseded",
    supersededBy: "AS 2441:2022",
    systems: ["hose-reel"],
    officialUrl: "https://store.standards.org.au/product/as-2441-2005",
    clauses: [
      { ref: "1", title: "Scope" },
      { ref: "2", title: "Application" },
      { ref: "3", title: "Referenced Documents" },
      { ref: "4", title: "Definitions" },
      { ref: "5", title: "Fire Hose Reel Assemblies" },
      { ref: "6", title: "Water Supply",
        covers: "What the reel has to be fed with. This is the duty a flow test is measured against, and the app takes the figure for the nominal hose diameter rather than assuming one \u2014 where it has no published duty for a size, it says so instead of guessing.",
        appFeature: "tools/hose-reel" },
      { ref: "7", title: "Connection Fitting" },
      { ref: "8", title: "Fire Hose Reel Pump" },
      { ref: "9", title: "Selection",
        covers: "Which reel, and how many. The app works from hose length and the area to be reached, and it is explicit that this is a check on what is installed rather than a design.",
        appFeature: "tools/hose-reel" },
      { ref: "10", title: "Location",
        covers: "Where the reels go, which is the question behind coverage: does the hose plus its throw actually reach the back of the room. A hose reel is the only asset on the book whose whole job is a distance, and nobody checks it once the reel is on the wall.",
        appFeature: "tools/hose-reel" },
      { ref: "11", title: "Mounting" },
      { ref: "12", title: "Commissioning Procedure" },
      { ref: "13", title: "Record of Installation" },
      { ref: "APPENDIX A", title: "Bibliography" },
    ],
  },
  {
    id: 'as-1905-1-2005',
    designation: "AS 1905.1:2005",
    title: "Components for the protection of openings in fire-resistant walls \u2014 Fire-resistant doorsets",
    scope: "product",
    status: "superseded",
    supersededBy: "AS 1905.1:2015",
    systems: ["door", "passive"],
    officialUrl: "https://store.standards.org.au/product/as-1905-1-2005",
    clauses: [
      { ref: "1.1", title: "Scope" },
      { ref: "1.2", title: "Application" },
      { ref: "1.3", title: "Normative Referenced Documents" },
      { ref: "1.4", title: "Definitions" },
      { ref: "2.1", title: "General" },
      { ref: "2.2", title: "Side-hung Doors, Including Double-acting Doorsets" },
      { ref: "2.3", title: "Sliding Doorsets" },
      { ref: "4.1", title: "General" },
      { ref: "4.2", title: "Variations Permitted Subject to A Formal Opinion" },
      { ref: "5.1", title: "General" },
      { ref: "5.2", title: "Doorsills" },
      { ref: "5.3", title: "Fixing of Doorframes" },
      { ref: "5.4", title: "Allowable Variations for Fixing of Doorframes" },
      { ref: "5.5", title: "Clearances",
        covers: "The gaps a fire doorset is installed to. This is the measurement taken at the door, and the app checks a measured gap against the figure for that doorset \u2014 where it holds no sourced figure for a case, it says so rather than passing the door on an assumed one.",
        appFeature: "tools/fire-door" },
      { ref: "5.6", title: "Hardware",
        covers: "The closers and latches, and whether latching applies at all for the doorset in front of you \u2014 which depends on the door type and how the leaf swings.",
        appFeature: "tools/fire-door" },
      { ref: "5.7", title: "Final Check" },
      { ref: "6.1", title: "Marking of Fire-resistant Doorsets",
        covers: "The tag on the door: what has to be on it, and from when. The app reads a tag, says which particulars are present and which are missing, and compares the FRL on it against the one the schedule calls for.",
        appFeature: "tools/fire-door" },
      { ref: "6.2", title: "Marking of Latchsets and Closers",
        covers: "The marking on the hardware rather than on the leaf, which is a separate check and a separate defect where it is missing.",
        appFeature: "tools/fire-door" },
      { ref: "6.3", title: "Evidence" },
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "Design Requirements" },
      { ref: "SECTION 3", title: "Determination of Fire Resistance" },
      { ref: "SECTION 4", title: "Variations from the Tested Specimen" },
      { ref: "SECTION 5", title: "Installation" },
      { ref: "SECTION 6", title: "Marking and Other Documentation" },
    ],
  },
  {
    id: 'as-2293-3-2005',
    designation: "AS 2293.3:2005",
    title: "Emergency escape lighting and exit signs for buildings \u2014 Emergency escape luminaires and exit signs",
    scope: "product",
    status: "superseded",
    systems: ["emergency-lighting"],
    officialUrl: "https://store.standards.org.au/product/as-2293-3-2005",
    clauses: [
      { ref: "1.1", title: "Scope" },
      { ref: "1.2", title: "Application" },
      { ref: "1.3", title: "Normative References" },
      { ref: "1.4", title: "Definitions" },
      { ref: "1.5", title: "Electromagnetic Compatibility" },
      { ref: "2.1", title: "Compliance with AS 3137" },
      { ref: "2.2", title: "Luminaire Classification" },
      { ref: "2.3", title: "Illumination at Switch on" },
      { ref: "2.4", title: "Marking" },
      { ref: "3.1", title: "Compliance with AS 3137" },
      { ref: "3.2", title: "Types of Exit Sign" },
      { ref: "3.3", title: "Appearance of Exit Sign Face" },
      { ref: "3.4", title: "Illumination" },
      { ref: "3.5", title: "Maximum Viewing Distances" },
      { ref: "3.6", title: "Marking" },
      { ref: "4.1", title: "General" },
      { ref: "4.2", title: "Suitability for Operating Temperatures" },
      { ref: "4.3", title: "Arrangement and Control" },
      { ref: "4.4", title: "Batteries" },
      { ref: "4.5", title: "Battery Chargers" },
      { ref: "4.6", title: "Control Equipment" },
      { ref: "4.7", title: "Electrical Requirements" },
      { ref: "4.8", title: "Self-contained Automatic Discharge Testing Facilities" },
      { ref: "4.9", title: "Marking" },
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "General Requirements for Emergency Escape Luminaires" },
      { ref: "SECTION 3", title: "General Requirements for Exit Signs" },
      { ref: "SECTION 4", title: "Particular Requirements for Self-contained Emergency" },
    ],
  },
  {
    id: 'as-2293-set-2005',
    designation: "AS 2293 Set:2005",
    title: "Emergency escape lighting and exit signs for buildings \u2014 Set",
    scope: "design",
    status: "superseded",
    systems: ["emergency-lighting"],
    officialUrl: "https://store.standards.org.au/product/as-2293-set-2005",
    clauses: [
      { ref: "1.1", title: "Scope" },
      { ref: "1.2", title: "Application" },
      { ref: "1.3", title: "Normative References" },
      { ref: "1.4", title: "Definitions" },
      { ref: "1.5", title: "Compliance with Other Standards" },
      { ref: "1.6", title: "New Designs and Innovations" },
      { ref: "1.7", title: "Alterations and Additions" },
      { ref: "2.1", title: "Scope of Section" },
      { ref: "2.2", title: "Duration of Operation" },
      { ref: "2.3", title: "Operation, Arrangement and Control" },
      { ref: "3.1", title: "Scope of Section" },
      { ref: "3.2", title: "Emergency Power Source" },
      { ref: "3.3", title: "Batteries and Their Installation" },
      { ref: "3.4", title: "Battery Charger Assembly" },
      { ref: "3.5", title: "Inverters" },
      { ref: "3.6", title: "Alarm Systems" },
      { ref: "4.1", title: "Scope of Section" },
      { ref: "4.2", title: "Single Point Systems" },
      { ref: "4.3", title: "Required Discharge Test Facilities" },
      { ref: "5.1", title: "Scope of Section" },
      { ref: "5.2", title: "Provision of Emergency Luminaires" },
      { ref: "5.3", title: "Acceptable Emergency Escape Luminaires" },
      { ref: "5.4", title: "Installations Employing Direct Lighting" },
      { ref: "5.5", title: "Installations Employing Indirect Lighting" },
      { ref: "5.6", title: "Lighting of Stairways" },
      { ref: "6.1", title: "Scope" },
      { ref: "6.2", title: "Required Locations" },
      { ref: "6.3", title: "Use of Externally Illuminated Signs" },
      { ref: "6.4", title: "Sign Colours" },
      { ref: "6.5", title: "Choice of Images" },
      { ref: "6.6", title: "Size of Pictorial Element" },
      { ref: "6.7", title: "Illumination" },
      { ref: "6.8", title: "Physical Conditions of Installation" },
      { ref: "6.9", title: "Identification and Marking of Exit Signs" },
      { ref: "7.1", title: "Scope of Section" },
      { ref: "7.2", title: "Circuit Voltage Drop" },
      { ref: "7.3", title: "Protection Against Overcurrent" },
      { ref: "7.4", title: "Protection of the Electrical Installation Against Fire" },
      { ref: "7.5", title: "Segregation or Identification of Submains" },
      { ref: "7.6", title: "Arrangement of Final Subcircuits" },
      { ref: "8.1", title: "Scope of Section" },
      { ref: "8.2", title: "Operating and Maintenance Manual" },
      { ref: "8.3", title: "Provision for the Recording of Maintenance" },
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "System Performance, Arrangement and Control" },
      { ref: "SECTION 3", title: "Emergency Power Supplies for Centrally Supplied" },
      { ref: "SECTION 4", title: "Provision of Charging Indication and Discharge Test" },
      { ref: "SECTION 5", title: "Design of Emergency Escape Luminaire Installation" },
      { ref: "SECTION 6", title: "Design of Exit Signs Installation" },
      { ref: "SECTION 7", title: "Installation of Electrical Wiring and Equipment for" },
      { ref: "SECTION 8", title: "Information Required for Maintaining the System" },
    ],
  },
  {
    id: 'as-4428-0-1997',
    designation: "AS 4428.0:1997",
    title: "Fire detection, warning, control and intercom systems \u2014 Control and indicating equipment, Part 0: General requirements",
    scope: "product",
    status: "superseded",
    systems: ["detection", "ews"],
    officialUrl: "https://store.standards.org.au/product/as-4428-0-1997",
    clauses: [
      { ref: "1.1", title: "Scope" },
      { ref: "1.2", title: "Application" },
      { ref: "1.3", title: "Referenced Documents" },
      { ref: "1.4", title: "Definitions" },
      { ref: "1.5", title: "General Requirements" },
      { ref: "1.6", title: "Compliance with Other Standards" },
      { ref: "1.7", title: "Interpretation of Specified Limiting Values" },
      { ref: "2.1", title: "General" },
      { ref: "2.2", title: "Electrical" },
      { ref: "2.3", title: "Mechanical" },
      { ref: "2.4", title: "Marking and Identification" },
      { ref: "2.5", title: "Software Controlled Equipment" },
      { ref: "2.6", title: "Warning Signal Tones" },
      { ref: "3.1", title: "Operating Instructions" },
      { ref: "3.2", title: "Installation and Maintenance Documentation" },
      { ref: "3.3", title: "Hazardous Locations" },
      { ref: "4.1", title: "General" },
      { ref: "4.2", title: "Functional Assessment" },
      { ref: "4.3", title: "Tests" },
      { ref: "4.4", title: "Compatibility Assessment" },
      { ref: "4.5", title: "Reporting" },
      { ref: "5.1", title: "Minor Variations" },
      { ref: "5.2", title: "Significant Variations" },
      { ref: "5.3", title: "Major Variations" },
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "Design and Construction" },
      { ref: "SECTION 3", title: "Documentation" },
      { ref: "SECTION 4", title: "Assessment of Compliance" },
      { ref: "SECTION 5", title: "Variation from Compliant Equipment" },
    ],
  },
  {
    id: 'as-2792-1992',
    designation: "AS 2792:1992",
    title: "Fire hose \u2014 Delivery layflat",
    scope: "product",
    status: "superseded",
    systems: ["hydrant", "hose-reel"],
    officialUrl: "https://store.standards.org.au/product/as-2792-1992",
    clauses: [
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "General Requirements" },
      { ref: "SECTION 3", title: "Performance Requirements" },
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "General Requirements" },
      { ref: "SECTION 3", title: "Performance Requirements" },
    ],
  },
  {
    id: 'as-nzs-4353-1995',
    designation: "AS/NZS 4353:1995",
    title: "Portable fire extinguishers \u2014 Aerosol type",
    scope: "product",
    status: "superseded",
    systems: ["extinguisher"],
    officialUrl: "https://store.standards.org.au/product/as-nzs-4353-1995",
    clauses: [
      { ref: "SECTION 1", title: "Scope and General" },
      { ref: "SECTION 2", title: "Materials of Construction" },
      { ref: "SECTION 3", title: "Design" },
      { ref: "SECTION 4", title: "Method of Operation" },
      { ref: "SECTION 5", title: "Charge" },
      { ref: "SECTION 6", title: "Performance Requirements" },
      { ref: "SECTION 7", title: "Test Requirements" },
      { ref: "SECTION 9", title: "Instructions and Markings" },
    ],
  },
  {
    id: 'as-2484-2-1991',
    designation: "AS 2484.2:1991",
    title: "Fire \u2014 Glossary of terms \u2014 Fire protection and firefighting equipment",
    scope: "product",
    status: "superseded",
    systems: [],
    officialUrl: "https://store.standards.org.au/product/as-2484-2-1991",
    clauses: [
      { ref: "SECTION 1", title: "General Terms and Phenomena of Fire" },
      { ref: "SECTION 2", title: "Structural Protection Against Fire" },
      { ref: "SECTION 3", title: "Fire Detection and Alarm" },
      { ref: "SECTION 4", title: "Firefighting Equipment and Engineering" },
      { ref: "SECTION 5", title: "Smoke Control" },
      { ref: "SECTION 6", title: "Evacuation and Means of Escape" },
      { ref: "SECTION 7", title: "Explosion Detection and Suppression" },
    ],
  },
  {
    id: 'as-1851-2012',
    designation: "AS 1851:2012",
    title: "Routine service of fire protection systems and equipment",
    scope: "maintenance",
    status: "current",
    systems: ["detection", "ews", "hydrant", "hose-reel", "extinguisher", "sprinkler", "pump", "passive", "door", "emergency-lighting"],
    officialUrl: "https://store.standards.org.au/product/as-1851-2012",
    note: "The maintenance standard this app is built around, and the one QDC MP 6.1 calls up in Queensland. Only the sections Safe QLD has confirmed against its own copy are listed \u2014 the rest are deliberately absent rather than guessed at, because citing the wrong section on a service record is worse than citing none.",
    clauses: [
      { ref: "1.16.2", title: "Critical defects",
        covers: "What AS 1851 classes as a critical defect. This is NOT the same test as the Queensland two-limb test in the Building Fire Safety Regulation, and the app keeps them separate for that reason.",
        appFeature: "work/defects" },
      { ref: "4.4.3", title: "Hydrant systems \u2014 schedule of routine service",
        covers: "The activity table for hydrants: what is done monthly, six-monthly, yearly and five-yearly.",
        appFeature: "tools/hydrant" },
      { ref: "6.4.1.2", title: "Detection and alarm \u2014 monthly schedule",
        covers: "The monthly activity table.",
        appFeature: "tools/routines" },
      { ref: "6.4.1.3", title: "Detection and alarm \u2014 six-monthly schedule",
        covers: "The six-monthly activity table.",
        appFeature: "tools/routines" },
      { ref: "6.4.1.4", title: "Detection and alarm \u2014 yearly schedule",
        covers: "The yearly activity table. This is the one most annual services are booked against.",
        appFeature: "tools/routines" },
      { ref: "6.4.1.5", title: "Detection and alarm \u2014 five-yearly schedule",
        covers: "The five-yearly activity table.",
        appFeature: "tools/routines" },
      { ref: "18.4.2.2", title: "Exhaust fans",
        covers: "Exhaust fan testing within smoke hazard management.",
      },
      { ref: "SECTION 4", title: "Fire hydrant systems",
        covers: "Routine service of hydrant systems. Table 4.4.3 is the schedule of activities and frequencies, and is what a hydrant service is booked against.",
        appFeature: "tools/hydrant" },
      { ref: "SECTION 6", title: "Fire detection and alarm systems",
        covers: "Routine service of detection and alarm systems, including the schedule tables the app maps its routines onto.",
        appFeature: "tools/routines" },
      { ref: "SECTION 10", title: "Portable fire extinguishers and fire blankets",
        covers: "Routine service of extinguishers and blankets \u2014 43% of the assets on Safe QLD\u2019s book.",
        appFeature: "tools/extinguisher" },
      { ref: "SECTION 17", title: "Passive fire and smoke containment systems",
        covers: "Passive systems. QDC MP 6.1 defines Queensland\u2019s passive fire safety installations by reference to this section.",
      },
    ],
  },
  {
    id: 'qdc-mp-6-1',
    designation: "QDC MP 6.1",
    title: "Queensland Development Code, Mandatory Part 6.1 \u2014 Maintenance of fire safety installations",
    scope: "code",
    status: "current",
    systems: [],
    officialUrl: "https://www.business.qld.gov.au/industries/building-property-development/building-construction/laws-codes-standards/queensland-development-code/current-parts",
    note: "Queensland Government material, published free. Unlike an Australian Standard this can be reproduced in full, and the app does so where it needs to.",
    clauses: [
      { ref: "Schedule 1", title: "Prescribed fire safety installations",
        covers: "The list of installations the maintenance obligation attaches to. The occupier statement enumerates every one of these, including the ones a building does not have.",
        appFeature: "occupier" },
      { ref: "Schedule 2", title: "Occupier statement",
        covers: "The approved form of the annual occupier statement.",
        appFeature: "occupier" },
      { ref: "\u2014", title: "Maintenance records",
        covers: "What a record of maintenance has to state. A form with perfect test results and no licence number fails this.",
        appFeature: "work/reports" },
    ],
  },
];
