import type { CatalogueSeedItem } from '@/db/catalogueRepo';

/**
 * The bundled parts catalogue, in chunks.
 *
 * GENERATED by scripts/chunk-catalogue.py — do not edit by hand.
 *
 * Each chunk is behind a function rather than imported, so requiring one does
 * not require them all: the seeder walks them in order, writes each and lets it
 * go, and peak memory is one chunk instead of 11,865 rows at once.
 */

export const CATALOGUE_CHUNKS: (() => CatalogueSeedItem[])[] = [
  () => require('./chunk-000.json') as CatalogueSeedItem[],
  () => require('./chunk-001.json') as CatalogueSeedItem[],
  () => require('./chunk-002.json') as CatalogueSeedItem[],
  () => require('./chunk-003.json') as CatalogueSeedItem[],
  () => require('./chunk-004.json') as CatalogueSeedItem[],
  () => require('./chunk-005.json') as CatalogueSeedItem[],
  () => require('./chunk-006.json') as CatalogueSeedItem[],
  () => require('./chunk-007.json') as CatalogueSeedItem[],
  () => require('./chunk-008.json') as CatalogueSeedItem[],
  () => require('./chunk-009.json') as CatalogueSeedItem[],
  () => require('./chunk-010.json') as CatalogueSeedItem[],
  () => require('./chunk-011.json') as CatalogueSeedItem[],
];

/** Total rows across every chunk, without loading any of them. */
export const CATALOGUE_SIZE = 11865;
