#!/usr/bin/env python3
"""Split the bundled catalogue into chunks the app can seed one at a time.

Metro inlines an imported JSON file into the JavaScript bundle, so requiring
the whole catalogue makes Hermes materialise every row as an object at once.
At twelve thousand parts that is a heap spike on first launch, on a phone, for
data that is written to SQLite and then never read from memory again.

Chunking bounds it: each file is required, seeded and released before the next
is touched, so peak memory is one chunk rather than the whole catalogue. The
index is generated too, because a hand-maintained list of requires is a thing
to forget to update.

Usage: chunk-catalogue.py <catalogue.json> <out-dir> [rows-per-chunk]
"""
import json
import sys
from pathlib import Path


def main(src, out_dir, per_chunk="1000"):
    rows = json.load(open(src))
    per = int(per_chunk)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    for stale in out.glob("chunk-*.json"):
        stale.unlink()

    chunks = [rows[i:i + per] for i in range(0, len(rows), per)]
    for i, chunk in enumerate(chunks):
        (out / f"chunk-{i:03d}.json").write_text(
            json.dumps(chunk, ensure_ascii=False, separators=(",", ":")) + "\n")

    requires = "\n".join(
        f"  () => require('./chunk-{i:03d}.json') as CatalogueSeedItem[],"
        for i in range(len(chunks)))

    (out / "index.ts").write_text(f'''import type {{ CatalogueSeedItem }} from '@/db/catalogueRepo';

/**
 * The bundled parts catalogue, in chunks.
 *
 * GENERATED by scripts/chunk-catalogue.py — do not edit by hand.
 *
 * Each chunk is behind a function rather than imported, so requiring one does
 * not require them all: the seeder walks them in order, writes each and lets it
 * go, and peak memory is one chunk instead of {len(rows):,} rows at once.
 */

export const CATALOGUE_CHUNKS: (() => CatalogueSeedItem[])[] = [
{requires}
];

/** Total rows across every chunk, without loading any of them. */
export const CATALOGUE_SIZE = {len(rows)};
''')
    print(f"{len(rows)} rows -> {len(chunks)} chunks of up to {per} in {out}")


if __name__ == "__main__":
    main(*sys.argv[1:4])
