/**
 * The service worker the web build needs to be worth having.
 *
 * A technician in a plant room has no signal, and a web page with no signal is
 * a dinosaur. The Android app is offline by construction; the browser is not,
 * unless the page keeps its own copy. This writes a worker that takes the
 * whole export into the browser's cache on first visit and serves it from
 * there afterwards, so the second opening works with the phone in flight mode
 * — which is the only way the link is any use on a site.
 *
 * The file list is generated rather than written by hand because every build
 * hashes its own names, and the version is derived from that list: a new build
 * is a new cache, and the old one is thrown away on activation rather than
 * left to fill the phone.
 */
const { createHash } = require('crypto');

/** Files never worth caching: the fallback page is index.html again, and the worker cannot cache itself. */
const SKIP = new Set(['404.html', 'sw.js', '.nojekyll']);

/**
 * @param files paths relative to the export root, as the server will serve them
 * @returns the JavaScript of the worker
 */
function serviceWorkerSource(files) {
  const keep = files.filter((f) => !SKIP.has(f)).sort();
  const version = createHash('sha256').update(keep.join('\n')).digest('hex').slice(0, 12);
  const list = JSON.stringify(keep.map((f) => './' + f), null, 2);
  return `/* Generated by scripts/webServiceWorker.js — do not edit. */
const CACHE = 'safeqld-${version}';
const FILES = ${list};

// Everything at once, on the first visit, because the visit after it is the
// one in the plant room. A single file failing (a stale CDN, a cancelled load)
// must not fail the install and leave the app with no cache at all.
self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await Promise.all(FILES.map((f) => cache.add(f).catch(() => {})));
    await self.skipWaiting();
  })());
});

// One build, one cache. The old one goes the moment the new worker takes over,
// so a phone does not carry a year of 11 MB bundles.
self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key !== CACHE && key.startsWith('safeqld-')) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // A deep link the router knows about is not a file on the server, so every
  // navigation is answered with the app itself and the path handed to it.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const shell = await cache.match('./index.html');
      if (shell) return shell;
      try { return await fetch(request); } catch { return new Response('Safe QLD is not in this browser\\u2019s cache yet, and there is no signal to fetch it.', { status: 503, headers: { 'Content-Type': 'text/plain' } }); }
    })());
    return;
  }

  // Cache first: the bundle and its assets are named by their own content, so
  // a cached copy can never be the wrong one.
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(request, { ignoreSearch: true });
    if (hit) return hit;
    const response = await fetch(request);
    if (response.ok && response.type === 'basic') cache.put(request, response.clone()).catch(() => {});
    return response;
  })());
});
`;
}

/** The line the page runs to install it. Kept here so the shell and the worker cannot drift. */
/**
 * The line the page runs to install it. Kept here so the shell and the worker
 * cannot drift.
 *
 * The path is worked out from the bundle's own `<script>` rather than written
 * as `./sw.js`, because a relative path is relative to the page: opened at a
 * deep link like /work/timesheets it asks the host for /work/sw.js, which is
 * not there, and the registration fails silently — leaving the app online-only
 * for exactly the person who followed a link to a screen. The bundle always
 * sits under `_expo/`, so everything before that is where the app lives,
 * whether it is served from a domain root or a project sub-path.
 */
const REGISTRATION = `
      if ('serviceWorker' in navigator) {
        window.addEventListener('load', function () {
          var bundle = document.querySelector('script[src*="_expo/static/js/web/"]');
          var src = bundle ? bundle.getAttribute('src') : '';
          var root = src.indexOf('_expo/') >= 0 ? src.slice(0, src.indexOf('_expo/')) : './';
          navigator.serviceWorker.register(root + 'sw.js', { scope: root })
            .catch(function () { /* a browser that refuses it still runs the app online */ });
        });
      }
`

module.exports = { serviceWorkerSource, REGISTRATION, SKIP };
