/**
 * The service worker the web build needs to be worth having.
 *
 * A technician in a plant room has no signal, and a web page with no signal is
 * a dinosaur. The Android app is offline by construction; the browser is not,
 * unless the page keeps its own copy. This writes a worker that takes the
 * whole export into the browser's cache on first visit and serves it from
 * there afterwards, so the second opening works with the phone in flight mode
 * — which is the only way the link is any use on a site.
 *
 * The file list is generated rather than written by hand because every build
 * hashes its own names, and the version is derived from that list: a new build
 * is a new cache, and the old one is thrown away on activation rather than
 * left to fill the phone.
 *
 * ---------------------------------------------------------------------------
 *
 * The half that was missing: a cache nobody ever leaves.
 *
 * Twenty documents were added to the standards library, published, and the
 * owner opened the app and could not find them. Nothing was wrong with the
 * site — the bundle on the server had them — and nothing was wrong with the
 * cache either, taken on its own terms. What was wrong is that there was no
 * way out of it. Every navigation was answered from the cache and nothing
 * revalidated; nothing ever called `registration.update()`; and a page already
 * open was never told a newer build existed. The browser's own check for a new
 * worker happens on navigation, and an app added to a home screen and left
 * running has none, so the old build could stay for as long as the tab did.
 *
 * Three things fix it, and they are the three below.
 *
 * **The page asks.** The registration script calls `update()` on load, when
 * the tab comes back to the front, when the network returns, and on a timer —
 * and registers with `updateViaCache: 'none'` so the check is a real request
 * for `sw.js` rather than a reread of the copy the CDN gave it ten minutes
 * ago.
 *
 * **A new worker waits rather than barging in.** `skipWaiting()` used to run
 * during install, which activates the new worker under the page that is still
 * showing — and activation deletes the old cache. A running page that then
 * asks for a font or a chunk gets a miss, and the file is not on the server
 * either, because a Pages deployment replaces the whole site and the old
 * hashed names are gone. So the new worker now waits until it is told, and it
 * is told by the page, at a moment the page chooses.
 *
 * **The moment it chooses.** A page less than half a minute old has nothing on
 * it worth keeping — nobody has typed anything yet — so it takes the new build
 * itself and reloads, which is what makes "open the app and it is current"
 * true. Later than that somebody is working, and the app asks instead, with a
 * line they can tap when they are ready. A flag in session storage means the
 * automatic one can happen at most once per tab, so a build that somehow fails
 * to satisfy the check cannot put the app in a reload loop.
 */
const { createHash } = require('crypto');

/** Files never worth caching: the fallback page is index.html again, and the worker cannot cache itself. */
const SKIP = new Set(['404.html', 'sw.js', '.nojekyll']);

/**
 * @param files paths relative to the export root, as the server will serve them
 * @returns the JavaScript of the worker
 */
function serviceWorkerSource(files) {
  const keep = files.filter((f) => !SKIP.has(f)).sort();
  const version = createHash('sha256').update(keep.join('\n')).digest('hex').slice(0, 12);
  const list = JSON.stringify(keep.map((f) => './' + f), null, 2);
  return `/* Generated by scripts/webServiceWorker.js — do not edit. */
const CACHE = 'safeqld-${version}';
const FILES = ${list};

// Everything at once, on the first visit, because the visit after it is the
// one in the plant room. A single file failing (a stale CDN, a cancelled load)
// must not fail the install and leave the app with no cache at all.
//
// A reload request on every one of them, and it is not a nicety. A plain
// cache.add goes through the browser's ordinary HTTP cache, and this site is
// served with max-age=600 — so inside ten minutes of a deployment the cache
// named after the NEW build could be filled with the PREVIOUS index.html,
// which names a bundle that is no longer on the server. That pairing then
// serves forever: a shell pointing at a 404.
//
// It does NOT call skipWaiting. Activating under a page that is still showing
// deletes the cache that page is reading from, and the files it would then ask
// the server for are gone — a deployment replaces the whole site, hashed names
// and all. So a new build waits here until the page says it is ready, which is
// the SKIP_WAITING message below.
self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await Promise.all(FILES.map((f) => cache.add(new Request(f, { cache: 'reload' })).catch(() => {})));
  })());
});

// The page's way of saying "now". It comes either from the app's own update
// prompt or from a freshly loaded page taking the new build on its own.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') void self.skipWaiting();
});

// One build, one cache. The old one goes the moment the new worker takes over,
// so a phone does not carry a year of 11 MB bundles.
self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key !== CACHE && key.startsWith('safeqld-')) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // A deep link the router knows about is not a file on the server, so every
  // navigation is answered with the app itself and the path handed to it.
  //
  // Answered from the cache first, always: a technician in a plant room with
  // no signal is the reason this worker exists, and a navigation that went to
  // the network first would give them nothing. The look for a newer build goes
  // alongside it rather than in front of it — the page is already painted by
  // the time that answer comes back, and what it does with the answer is the
  // registration script's business.
  if (request.mode === 'navigate') {
    event.waitUntil(self.registration.update().catch(() => {}));
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const shell = await cache.match('./index.html');
      if (shell) return shell;
      try { return await fetch(request); } catch { return new Response('Safe QLD is not in this browser\\u2019s cache yet, and there is no signal to fetch it.', { status: 503, headers: { 'Content-Type': 'text/plain' } }); }
    })());
    return;
  }

  // Cache first: the bundle and its assets are named by their own content, so
  // a cached copy can never be the wrong one.
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(request, { ignoreSearch: true });
    if (hit) return hit;

    // Not in this build's cache. Before the network, look in the ones this
    // worker is replacing: a page that was claimed mid-session is still running
    // the bundle it was built against, and the chunk it asks for next exists
    // only in the cache that build left behind.
    //
    // Named caches rather than caches.match, which searches every cache on the
    // origin. This app is served from a shared github.io host, so that would
    // include whatever some other project of the owner's has put there.
    for (const key of await caches.keys()) {
      if (key === CACHE || !key.startsWith('safeqld-')) continue;
      const older = await (await caches.open(key)).match(request, { ignoreSearch: true });
      if (older) return older;
    }

    try {
      const response = await fetch(request);
      if (response.ok && response.type === 'basic') cache.put(request, response.clone()).catch(() => {});
      return response;
    } catch {
      // A rejected respondWith is a network error the page cannot tell apart
      // from a broken app. An answer that says "not here" is one it can.
      return new Response('', { status: 504, statusText: 'Safe QLD is offline and this file is not in the cache.' });
    }
  })());
});
`;
}

/** How often an open app asks the server whether the build has moved on. */
const UPDATE_CHECK_EVERY_MS = 15 * 60 * 1000;

/**
 * How young a page has to be to take a new build without asking.
 *
 * Long enough to cover the check that runs on load and the round trip it
 * makes; short enough that nobody has typed a defect into a form yet.
 */
const FRESH_PAGE_MS = 30 * 1000;

/**
 * The event the app listens for, and the function it calls back.
 *
 * A DOM event rather than an import, because this script runs in the page's
 * head before the bundle exists — there is nothing to import it into. The
 * React side is src/components/WebUpdatePrompt.web.tsx, which adds a listener
 * and calls the function when the person taps.
 */
const UPDATE_READY_EVENT = 'safeqld:update-ready';
const APPLY_UPDATE_FUNCTION = '__safeqldApplyUpdate';

/**
 * The flag beside the event, for a listener that was not there to hear it.
 *
 * This script runs in the head and the React tree mounts some time later, so
 * an update found early would be announced to nobody. The flag is the same
 * news in a form that keeps, and the component reads it on mount.
 */
const UPDATE_READY_FLAG = '__safeqldUpdateReady';

/**
 * The line the page runs to install it. Kept here so the shell and the worker
 * cannot drift.
 *
 * The path is worked out from the bundle's own `<script>` rather than written
 * as `./sw.js`, because a relative path is relative to the page: opened at a
 * deep link like /work/timesheets it asks the host for /work/sw.js, which is
 * not there, and the registration fails silently — leaving the app online-only
 * for exactly the person who followed a link to a screen. The bundle always
 * sits under `_expo/`, so everything before that is where the app lives,
 * whether it is served from a domain root or a project sub-path.
 *
 * Written in the old dialect on purpose: this is inline script in the head of
 * a page, running before anything has been transpiled or polyfilled, and every
 * one of its failures is swallowed. A browser that cannot do service workers,
 * cannot do session storage, or refuses the registration still runs the app —
 * online, the way it did before any of this existed.
 */
const REGISTRATION = `
      if ('serviceWorker' in navigator) {
        (function () {
          var CHECK_EVERY_MS = ${UPDATE_CHECK_EVERY_MS};
          var FRESH_PAGE_MS = ${FRESH_PAGE_MS};
          var TOOK_ONE = 'safeqld.tookUpdate';
          var opened = Date.now();
          var offered = null;
          var applying = false;

          // Private browsing and a locked-down profile both throw on this
          // rather than returning null, and neither is a reason to fail.
          function tookOneAlready() {
            try { return sessionStorage.getItem(TOOK_ONE) === '1'; } catch (e) { return false; }
          }
          function rememberTookOne() {
            try { sessionStorage.setItem(TOOK_ONE, '1'); } catch (e) {}
          }

          function apply() {
            if (applying || !offered) return;
            applying = true;
            rememberTookOne();
            offered.postMessage({ type: 'SKIP_WAITING' });
          }
          window.${APPLY_UPDATE_FUNCTION} = apply;

          // The new worker has taken over, so the code this page is running is
          // the old build. Reload only where this page asked for it: a reload
          // nobody asked for, in the middle of a form, is worse than a stale tab.
          navigator.serviceWorker.addEventListener('controllerchange', function () {
            if (applying) window.location.reload();
          });

          function offer(worker) {
            if (!worker || worker === offered) return;
            offered = worker;
            // A page this young has nothing on it worth keeping, so it takes
            // the build itself. Once per tab, so a build that cannot satisfy
            // the check cannot put the app in a loop.
            if ((Date.now() - opened) < FRESH_PAGE_MS && !tookOneAlready()) { apply(); return; }
            // The flag before the event: the app's own prompt may not have
            // mounted yet, and it reads the flag when it does.
            window.${UPDATE_READY_FLAG} = true;
            try { window.dispatchEvent(new CustomEvent('${UPDATE_READY_EVENT}')); } catch (e) {}
          }

          function watch(reg) {
            // Already sitting there from a previous visit. The controller test
            // is what tells a new build apart from the very first install,
            // which has nothing to replace and no one to tell.
            if (reg.waiting && navigator.serviceWorker.controller) offer(reg.waiting);
            reg.addEventListener('updatefound', function () {
              var arriving = reg.installing;
              if (!arriving) return;
              arriving.addEventListener('statechange', function () {
                if (arriving.state === 'installed' && navigator.serviceWorker.controller) offer(arriving);
              });
            });
          }

          window.addEventListener('load', function () {
            var bundle = document.querySelector('script[src*="_expo/static/js/web/"]');
            var src = bundle ? bundle.getAttribute('src') : '';
            var root = src.indexOf('_expo/') >= 0 ? src.slice(0, src.indexOf('_expo/')) : './';
            navigator.serviceWorker.register(root + 'sw.js', { scope: root, updateViaCache: 'none' })
              .then(function (reg) {
                watch(reg);
                var check = function () { try { reg.update(); } catch (e) {} };
                check();
                setInterval(check, CHECK_EVERY_MS);
                // The moments an app is most likely to have fallen behind: it
                // has just come back to the front, or the signal has returned.
                document.addEventListener('visibilitychange', function () {
                  if (document.visibilityState === 'visible') check();
                });
                window.addEventListener('online', check);
              })
              .catch(function () { /* a browser that refuses it still runs the app online */ });
          });
        })();
      }
`

module.exports = {
  serviceWorkerSource,
  REGISTRATION,
  SKIP,
  UPDATE_READY_EVENT,
  APPLY_UPDATE_FUNCTION,
  UPDATE_READY_FLAG,
  UPDATE_CHECK_EVERY_MS,
  FRESH_PAGE_MS,
};
